/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "projeto_1.h"

bool_t
xdr_vetor (XDR *xdrs, vetor *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->array, 500,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_maior_menor (XDR *xdrs, maior_menor *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->maior_menor, 2,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
